### ISSUE TITLE
Bug report: regular crashes

### ISSUE THREAD

**Issue by Amaras** [pascalaubry/papi-web#13]
[FR]
Cette issue est ouverte pour permettre de centraliser les rapports de bug générique à des fins de documentation, qu'ils soient directement envoyés par les utilisateurs ici, soit envoyés par mail à un développeur.
Les rapports doivent contenir au moins le fichier log du serveur, avec préférentiellement la configuration de l'événement anonymisée (en particulier en enlevant les mots de passe et/ou identifiants).

<hr>

[EN]
This issue has been opened to centralize generic bug reports for documentation purposes, whether they are sent here directly by users, or sent by email to a developer.
Reports must contain at a minimum the log file written by the server, and preferably the anonymized event configuration (in particular, logins and passwords have to be removed).

**Comment by Amaras** [comment]
# [FR] Rapport de bug

Ce rapport ne contient pas de log ni de configuration pour l'instant, en attendant une discussion avec l'arbitre principal du tournoi.

## Tournoi concerné
Championnat scolaire des écoles d'Ille-et-Vilaine 2024, ayant eu lieu le 17 janvier 2024.

## Version utilisée
release v2.1.1 

## Symptômes
Lenteur puis absence de réponse du serveur lors de l'utilisation d'écrans rotatifs. Les tablettes de saisies affichent l'indicateur en attendant le retour du serveur.

## Action prise suite aux symptômes
Tentatives de redémarrage du serveur n'ayant rien résolu, puis abandon de l'utilisation de papi-web.

## Notes supplémentaires
La personne ayant écrit ce rapport n'étant pas l'arbitre principal ou la personne responsable de papi-web, il n'est pas possible de détailler plus.

**Comment by pascalaubry** [comment]
Removed ODBC pooling in 2.1.8, successfully tested by Ludovic Perche.
Hoping the fix will do the job for all, still leaving this issue opened (waiting for more feedback).

**Comment by pascalaubry** [comment]
Server crashes observed up to version 2.3 were not reproduced with 2.4, closing.
