### ISSUE TITLE
Generation of build (with export script)

### ISSUE THREAD

**Issue by adrienave** [pascalaubry/papi-web#22]
I tried to run `export.py` to generate a build of the application from my source repo, it went well, but I noticed a few issues with what has been generated:

~- [] Build is put in the parent folder of the folder from when the script is run, it was confusing for me since usually, as an user, you expect output to be generated inside of the current location. `EXPORT_DIR` could be changed to address this issue.~
- [x] `bin` folder is generated as a file instead of a folder, making the `server.bat` script not working. Check attachments for more details.
It could be related to my configuration so I would put it here: Windows 10.

![image](https://github.com/papi-web-org/papi-web/assets/49407726/c137dc07-1395-44e0-be15-e7dfc0774baf)
![image](https://github.com/papi-web-org/papi-web/assets/49407726/661bca3b-ff5e-4024-a722-d83c38206b32)

Also, I think it could be nice to have some kind of simple technical README, for new people who want to contribute to the project (it would make their integration simpler, and maybe motivate more people to join).

- [x] Add (technical) README describing required stack to start the project, how to build the executable and maybe more.

**Comment by Amaras** [comment]
How to use the project without exporting and using the exported files was purposefully left undocumented until now.
I added a `--path` option (defaulting to `.`) for use in different configurations.

We should probably add a contribution documentation indeed, that's in the works.
For now, here's the base command I use when using the code version: `python papi-web.py --path export-data` (add `-c`, `-s`, `-t` or `-f`, depending on your usage.)

**Comment by adrienave** [comment]
> How to use the project without exporting and using the exported files was purposefully left undocumented until now.
> I added a `--path` option (defaulting to `.`) for use in different configurations.

Right, it's me who didn't check things more carefully and thought `export.py` was intended to be used for generating local build, but I guess it's more like for releasing a new version, and `papi-web.py` is for running local version of the application.
I'm removing the first item then.
I'm wondering about the second one though (bin being a file instead of folder), but maybe it doesn't matter if `export.py` is supposed to be run only from a specific server and it's generating things properly there.

> We should probably add a contribution documentation indeed, that's in the works.
> For now, here's the base command I use when using the code version: python papi-web.py --path export-data (add -c, -s, -t or -> f, depending on your usage.)

Thanks for the advice, help section of this script is describing things clearly anyway.

**Comment by pascalaubry** [comment]
@adrienave Got it: I have a local empty /export-data/bin folder that is not pushed, fixed in export.py.

**Comment by pascalaubry** [comment]
@adrienave Added basic 83-dev-setup.md and 84-export.md, feel free to enhance.
