### ISSUE TITLE
Allow the use of several timers in an event

### ISSUE THREAD

**Issue by Amaras** [pascalaubry/papi-web#26]
During the setup for an event with several tournaments which don't have the same start times or cadence, I realized that only one timer is available.

## Current solution
One of two possible solutions:
1. Spin up two different servers with different ports, and set up two events with a distinct timer.
2. Use one timer and add events for each (which can interfere with each other).

## Proposed solution
Allow the use of distinct timers in an event (undecided syntax)
If several timers are configured, use `show_timer = <timer_id>` and disallow `show_timer = on` in screens and tournaments

**Comment by pascalaubry** [comment]
Possible in [2.4.0](https://github.com/papi-web-org/papi-web/releases/tag/2.4.0).
