### ISSUE TITLE
Improve `results` screens

### ISSUE THREAD

**Issue by Amaras** [pascalaubry/papi-web#27]
During the setup of a tournament, I realized that it would be cool to limit the tournaments used for the screens of type `results`, which is not something currently possible.

We'll see more about that later.

EDIT: task list:

- [x] Allow restriction of tournaments in the configuration of `results` screens (#35, merged)
- [x] Allow configuration of results display time
- [ ] Make `results` screen searchable for arbiters
- [x] Allow deletion of results for arbiters

**Comment by Amaras** [comment]
Changed the title to bring forward several more improvement ideas:
1. Make the time during which the results are shown configurable (namely depending on the  regulation's appeal time, default to 60 minutes).
2. Make the results searchable (ignore the configured time) on player name.
3. Allow deletion of results (only on admin permission, obviously).

**Comment by pascalaubry** [comment]
1 could be easily added in 2.4.2.
2 and 3 should be enabled on admin screens only.

**Comment by pascalaubry** [comment]
1 and 3 were added to 2.4.2.
2 will wait for the evolution of the admin screens for tournament management

**Comment by pascalaubry** [comment]
Last task "Make results screen searchable for arbiters" will wait, closing this issue.
