### ISSUE TITLE
Add new arbiter screen type to allow overwrite results and input non-player-facing results

### ISSUE THREAD

**Issue by Amaras** [pascalaubry/papi-web#29]
Arbiters should be able to access this screen from any update screen, probably with an authentication method (band-aid solution for now: define a password in the event file, and encrypt it in memory, disable this type of screen if no password defined).

The main features of this screen should be:

1. For any pairing, if a result has been given, allow the arbiter to change the result with any possible result.
2. Allow the arbiter to input non-player-facing results, namely forfeits (at some point in the future: non-standard results)
3. A way to safely get back to the previous update screen once done (the arbiter needs to authenticate again to get to this screen).

Those features aside, this screen should probably be like any update screen.

**Comment by pascalaubry** [comment]
Features 1 and 2 were added to 2.4.2.

**Comment by pascalaubry** [comment]
Feature 3 is too hard to implement now and will wait for new admin screens.
