### ISSUE TITLE
Check-in process is hard to use in practice

### ISSUE THREAD

**Issue by timothyarmes** [pascalaubry/papi-web#30]
I've just arbited a small tournament for under 18s and tried out the new check-in feature for the first time.  While it worked functionally, it's actually quite awkward to use in practice. 

For context, I'm using an iPad to allow players to check-in and enter results.  While entering results presents no issues for the player, checking in requires being **very** accurate when taping the checkboxes next to the names.  On many occasions the players accidentally checked in the player above or below them, reducing my confidence in the accuracy of the pointage.  Even when it worked, it ofter took several attempts to click the right place.

I'd like to see the interface improved to follow the pattern of the results input : allow players to click anywhere on their name row, then pop up a box, with their name, to confirm or cancel the pointage.

**Comment by Amaras** [comment]
Thank you for opening this issue.
The check-in feature is definitely not in its final state, as we aim to provide a better interface for the check-in process in a future version.

In the meantime, I'd recommend either zooming in to improve the accuracy of the check-in, or using ChessEvent and checking-in on the platform.

I'll keep you posted and leave this issue open until we work on the new check-in interface.
