### ISSUE TITLE
Rotators are broken

### ISSUE THREAD

**Issue by timothyarmes** [pascalaubry/papi-web#41]
In v2.40 the rotator screens are broken.

1. It's not possible to access the rotators tab
2. Fixing that bug (see below) enables the tab to work, but the rotators don't rotate

I can't currently push to the project to make a PR, I don't wish to fork it, so:

For the tab bug, in `user_event.html`, line 89, the rotator_sreen_index parameter needs adding:

`card_url=url_for('user-rotator', event_uniq_id=user_event.uniq_id, rotator_id=rotator.id, rotator_screen_index=0),
`

For the rotation bug, in `user_screen.html` the index needs incrementing:

`hx-get="{{ url_for('user-rotator', event_uniq_id=user_event.uniq_id, rotator_id=rotator.id, rotator_screen_index=rotator_screen_index+1) }}"
`

**Comment by pascalaubry** [comment]
Fixed in [2.4.1](https://github.com/papi-web-org/papi-web/releases/tag/2.4.1), thanks.
