### ISSUE TITLE
[BUG] Database migration issue ?

### ISSUE THREAD

**Issue by timothyarmes** [pascalaubry/papi-web#43]
## Descirption du bug

Upon installing version version 2.4.2 over 2.4.0, and running ffe.bat, I had these errors:

Votre version de Papi-web est à jour
Mise à jour de la base de données championnat-drome-2024.db...
La base de données championnat-drome-2024.db a été mise à jour en version 2.4.2.
Mise à jour de la base de données championnat-drome-2024.db...
La base de données championnat-drome-2024.db ne peut être mise à jour en version 2.4.2.
Mise à jour de la base de données CJ-R1-Valence.db...
La base de données CJ-R1-Valence.db a été mise à jour en version 2.4.2.
Mise à jour de la base de données CJ-R1-Valence.db...
La base de données CJ-R1-Valence.db ne peut être mise à jour en version 2.4.2.
Mise à jour de la base de données CJ-R2-Romans.db...
La base de données CJ-R2-Romans.db a été mise à jour en version 2.4.2.
Mise à jour de la base de données CJ-R2-Romans.db...
La base de données CJ-R2-Romans.db ne peut être mise à jour en version 2.4.2.
Aucun évènement trouvé

It's hard to understand what happened.  For each database it first tells me that it was updated correctly, then tells me that it couldn't update it.  

It seems to have worked, but I'm concerned that it hasn't...

**Comment by pascalaubry** [comment]
Database upgrade was done twice when opening databases in r/o mode, fixed in 2.4.3.
