### ISSUE TITLE
Feature request: licence check

### ISSUE THREAD

**Issue by timothyarmes** [pascalaubry/papi-web#45]
I may be mistaken, but I not found an easy way to check that all players have the appropriate FFE licence using Papi.

This would be a really useful feature to have in Papi-Web.

**Comment by Amaras** [comment]
I don't know if that is easily feasible.
Papi allows arbiters to enter non-licenced players to the database, and licenced players have a mark in the database window when you search for their name (before registering them).
I am not sure if I want to annoy Erick Mouret even more by fetching people's data on the online database, so we'd need to have the offline database up to date and check their licence level there.

ChessEvent checks automatically against the federal database during registration, so it's technically already done in Brittany (although not necessarily elsewhere).

**Comment by timothyarmes** [comment]
When you double click on a player in Papi you can see the licence, so it's in the Papi file.

**Comment by Amaras** [comment]
Indeed, but it relies on correct input of information, and the information in the papi file being up-to-date, despite possible changes to this information in-between creation and use.
EDIT: The only real up-to-date information we can rely on is the live database, and maybe the daily database snapshot.

**Comment by timothyarmes** [comment]
Sure, we're relying on the Papi database being up to date. We can easily run the Papi's synchronisation feature if needed.

Currently it's virtually impossible to ensure that everyone has a licence. If we could add an option to display the A, B or - next to each player's name (probably on a private screen) it would already be a huge help.

**Comment by Amaras** [comment]
I see where you're coming from.
We can add that to the to-do list.
I think we could add that to the check-in screen on admin auth

**Comment by pascalaubry** [comment]
I agree with both of you : short term needed feature, with a conection to the online FFE database or an offline copy.
More generally other connectors should be provided for all the federations when possible, and of course a main connector to the Fide data itself.

**Comment by timothyarmes** [comment]
This is an example of what we can easily do today:

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/3f7453f1-558c-45c5-986d-20242f888236">

**Comment by Amaras** [comment]
> [...] a main connector to the Fide data itself.

I think it's needed, but it's only useful for fetching the up-to-date ratings, it's useless for fetching national licence and ratings (for 0-rating players in the FIDE database).

@timothyarmes I think you can put that in your PR, it's still an improvement over what we currently have.
