### ISSUE TITLE
[BUG] Excessive network use

### ISSUE THREAD

**Issue by Amaras** [pascalaubry/papi-web#49]
This issue follows a report from a user.

For scholastic tournaments, Papi-web led to 4.8GB of data use, according to the user's phone data report.

ChessEvent was not used, and export to the FFE website was stopped way too soon to make a difference.
It might be just an artefact of the way the phone tallies the data use, but limiting this is probably a good idea anyway.

**Comment by pascalaubry** [comment]
An excessive number of downloads of the Bootstrap JS has been fixed in 2.4.5 (470kb/req), please reopen if needed.
