### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tfondrat** [pascalaubry/papi-web#53]
## Description du bug
Problème de dépendenances lors de l'installation sous ubuntu 

## Comment reproduire le bug
Étapes pour reproduire le bug :

Lignes de commandes lancées

**_git clone https://github.com/papi-web-org/papi-web.git
cd papi-web/
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install --upgrade pip
python3 --version   ------>    Python 3.12.1    
python3 -m pip install -r requirements.txt_**

## Comportement attendu

Installation fonctionnelle!

## Environnement d'utilisation
- OS : #49~22.04.1-Ubuntu
- Version de Papi-web : 2.4 ( dernière version ) 
- Date: 23 Novembre 6;19 UTC+1 

## Contexte additionnel
INFO: pip is looking at multiple versions of pydantic to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 57) and pydantic-core~=2.27.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic-core~=2.27.0
    pydantic 2.9.2 depends on pydantic-core==2.23.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by tfondrat** [comment]
Résolu en changeant 
pydantic-core~=2.27.0 en pydantic-core==2.23.4
Est-il possible d'ajouter sqlite3 ? ( pas testé! ) 
Installé sqlite3 aves les commande suivantes : 
wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
tar xvf Python-3.12.0.tgz
cd Python-3.12.0
./configure --enable-loadable-sqlite-extensions
make
sudo make install

**Comment by Amaras** [comment]
Bonjour,

Merci pour le rapport de bug.
Cette dépendance est effectivement un problème, nous souhaitons retirer les dépendances transitives, ce qui éliminerait complètement ce genre de problèmes.

Quel pilote Access utilisez-vous pour faire fonctionner l'accès aux boules papi ?

**Comment by Amaras** [comment]
Le problème devrait être résolu avec la version actuelle, je ferme ce rapport
